version: '3.4'

x-base: &x-base
  volumes:
  - .:$PWD:cached
  working_dir: $PWD
  command: sshd

services:
  php:
    <<: *x-base
    image: "minidocks/php-tools:${PHP_VERSION:-8.0}"

  node:
    <<: *x-base
    image: "minidocks/node:${NODE_VERSION:-12}"
